# Generated by Django 4.2.6 on 2023-10-31 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ExpSys', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense_report',
            name='cost_center',
            field=models.CharField(default='NEMM', max_length=100, verbose_name='Cost Center'),
        ),
        migrations.AddField(
            model_name='expense_report',
            name='final_action',
            field=models.SmallIntegerField(choices=[(1, 'Draft'), (2, 'Sent'), (3, 'Completed')], default=1),
        ),
        migrations.AddField(
            model_name='expense_report',
            name='finanDepart',
            field=models.SmallIntegerField(choices=[(1, 'Draft'), (2, 'Sent'), (3, 'Completed')], default=1),
        ),
        migrations.AddField(
            model_name='expense_report',
            name='line_manager_action',
            field=models.SmallIntegerField(choices=[(1, 'Draft'), (2, 'Sent'), (3, 'Completed')], default=1),
        ),
    ]
