# Generated by Django 4.2.6 on 2023-10-31 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ExpSys', '0002_expense_report_cost_center_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense_report',
            name='line_manager_comments',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
