# Generated by Django 4.2.6 on 2023-10-31 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ExpSys', '0003_alter_expense_report_line_manager_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='finalCon',
            field=models.SmallIntegerField(choices=[(1, False), (2, True)], default=1),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='linemgr',
            field=models.SmallIntegerField(choices=[(1, False), (2, True)], default=1),
        ),
        migrations.AlterField(
            model_name='expense_report',
            name='final_action',
            field=models.SmallIntegerField(choices=[(1, 'initial'), (2, 'received'), (3, 'reject'), (4, 'approved')], default=1),
        ),
        migrations.AlterField(
            model_name='expense_report',
            name='finanDepart',
            field=models.SmallIntegerField(choices=[(1, 'initial'), (2, 'received'), (3, 'action_required'), (4, 'doc_required'), (5, 'approved')], default=1),
        ),
        migrations.AlterField(
            model_name='expense_report',
            name='line_manager_action',
            field=models.SmallIntegerField(choices=[(1, 'initial'), (2, 'received'), (3, 'reject'), (4, 'approved')], default=1),
        ),
    ]
